baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "nograsswillgrow"
    subtitle = ""
    keywords = ""
    copyright = "plz don't steal content thx"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nograsswillgrow â€” a blog by Joshua Grady"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "instagram"
        name = "Instagram"
        url = "https://www.instagram.com/nograsswillgrow/"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/nograsswillgrow"

[author]
    name = "Joshua Grady"
